### ISSUE TITLE
Question: Why the blacklist of functions?

### ISSUE THREAD

**Issue by duclet** [mntnoe/babel-plugin-transform-helper-modules#2]
Hi, I was just wondering why the interop functions are blacklisted? Looking at their code, I don't see any particular reason why it needs to be blacklisted since all of its variable are either local or passed in.

**Comment by mntnoe** [comment]
I don't know, to be honest. This plugin is just a scaled down version of babel-plugin-transform-runtime, with the core-js part stripped out, as we needed the bundled code to be independent of polyfills.

The original code can be found here:

https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js

Maybe you can dig out what the rationale behind the blacklist.

**Comment by mntnoe** [comment]
On second thought: You could likely run into trouble in some configurations, when you require() the default export from interopRequireDefault.js, which will require() interopRequireDefault etc.
